const menu = [
  {
    id: 1,
    title: "Lunch Meals",
    category: "Lunch",
    price: 120,
    image: `https://images.unsplash.com/photo-1625398407796-82650a8c135f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80`,
    description: `A meal is an eating occasion that takes place at a certain time and includes consumption of food. The names used for specific meals in English vary, depending on the speaker's culture, the time of day, or the size of the meal.`,
  },
  {
    id: 2,
    title: "Idlly",
    category: "Breakfast",
    price: 60,
    image: `https://wynfluenzfoundation.com/wp-content/uploads/2021/11/idly4.jpg`,
    description: `dli or idly  is a type of savoury rice cake, originating from the Indian subcontinent, popular as breakfast foods in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented black lentils (de-husked) and rice.`,
  },
  {
    id: 3,
    title: "Dosa",
    category: "Breakfast",
    price: 60,
    image: `https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg`,
    description: `A dosa, also called dosai, dosey, or dosha, is a thin pancake in South Indian cuisine made from a fermented batter of ground black lentils and rice. Dosas are popular in South Asia as well as around the world. Dosas are served hot, often with chutney and sambar`,
  },
  {
    id: 4,
    title: "Poori",
    category: "Breakfast",
    price: 120,
    image: `https://www.awesomecuisine.com/wp-content/uploads/2020/03/poori-masala-kizhangu.jpg`,
    description: `Puri is a deep-fried bread made from unleavened whole-wheat flour that originated in the Indian subcontinent. It is eaten for breakfast or as a snack or light meal. It is usually served with a savory curry or bhaji, as in puri bhaji, but may also be eaten with sweet dishes`,
  },
  {
    id: 5,
    title: "Pongal",
    category: "Breakfast",
    price: 60,
    image: `https://www.yummytummyaarthi.com/wp-content/uploads/2011/09/IMG_0503.jpg`,
    description: `Pongal, also known as pongali or huggi, is an Indian rice dish. In Tamil, pongal means boil or bubbling up. The two varieties of pongal are chakarai pongal, which is sweet, and venn pongal, which is savoury and made with clarified butter.,
    `,
  },
  {
    id: 6,
    title: "Chapathi",
    category: "Dinner",
    price: 60,
    image: `https://satvikorganic.com/wp-content/uploads/2021/10/CHAPATHI.jpg`,
    description: `Chapati, also known as roti, rotli, safati, shabaati, phulka, chapo, poli, and roshi, is an unleavened flatbread originating from the Indian subcontinent and staple in India, Nepal, Bangladesh, Pakistan, Sri Lanka, East Africa, Arabian Peninsula and the Caribbean`,
  },
  {
    id: 7,
    title: "Parota",
    category: "Dinner",
    price: 50,
    image: `https://www.shethepeople.tv/wp-content/uploads/2020/06/parota-e1591966912214.jpg`,
    description: `Parotta or Porotta is a layered Indian and Sri Lankan flatbread made from Maida or Atta, alternatively known as flaky ribbon pancake`,
  },
  {
    id: 8,
    title: "Curd Rice",
    category: "Lunch",
    price: 60,
    image: `https://upload.wikimedia.org/wikipedia/commons/5/58/Curd_Rice.jpg`,
    description: `Curd rice, also called yogurt rice, is a dish originating from India. The word "curd" in Indian English refers to unsweetened probiotic yogurt. It is most popular in the South Indian states of Tamil Nadu, Kerala, Karnataka, Telangana and Andhra Pradesh; and also in Maharashtra.`,
  },
  {
    id: 9,
    title: "Sambhar Rice",
    category: "Lunch",
    price: 60,
    image: `https://t4.ftcdn.net/jpg/04/02/39/73/360_F_402397317_dJoOKzC65pdh4M7Mk9fccdTVl8YzeDK7.jpg`,
    description: `An extremely popular south indian lunch or dinner meal combo recipe made with rice and a combination of sambar spices`,
  },
  {
    id: 10,
    title: "Chole Bhature",
    category: "Dinner",
    price: 100,
    image: `https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/x6ay3mwbkfaj5flgslow`,
    description: `Chole bhature is a food dish popular in the Northern areas of the Indian subcontinent. It is a combination of chana masala and bhatura/puri, a deep-fried bread made from maida. Although it is known as a typical Punjabi dish, It is originally a culinary dish of Delhi and Uttar Pradesh.`,
  },
];

export default menu;
